import React from 'react'
import { HashLink } from 'react-router-hash-link'
const About = () => {
  return (
    <>
<h1><HashLink to={"/about#h1"}> Heading-1</HashLink></h1>
<h1><HashLink to={"/about#h2"}> Heading-2</HashLink></h1>
<h1><HashLink to={"/about#h3"}> Heading-3</HashLink></h1>
<h1><HashLink to={"/about#h4"}> Heading-4</HashLink></h1>
<h1><HashLink to={"/about#h5"}> Heading-5</HashLink></h1>
<h1><HashLink to={"/about#h6"}> Heading-6</HashLink></h1>
<h1><HashLink to={"/about#h7"}> Heading-7</HashLink></h1>
<h1><HashLink to={"/about#h8"}> Heading-8</HashLink></h1>
<h1><HashLink to={"/about#h9"}> Heading-9</HashLink></h1>
<h1><HashLink to={"/about#h10"}> Heading10</HashLink></h1>

    <h1>About pageeee</h1>
    <h1 id='h1'>Heading-1</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1 id='h2'>Heading-2</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1 id='h3'>Heading-3</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1 id='h4'>Heading-4</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1 id='h5'>Heading-5</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1 id='h6'>Heading-6</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1 id='h7'>Heading-7</h1>
    <p id='h8'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1>Heading-8</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1 id='h9'>Heading-9</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1 id='h10'>Heading-10</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
     <h1 id='h11'>Heading-11</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab possimus impedit tenetur molestiae ea aperiam provident officia, sint cumque neque iste nisi perferendis! Modi, error excepturi autem, recusandae odio quis optio accusamus laborum vel, magnam eos quos quibusdam delectus! Vitae corrupti reprehenderit dicta blanditiis id laboriosam itaque nam eaque Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam quo iusto nulla nobis expedita accusamus ratione, deleniti exercitationem repellat nesciunt nam accusantium eius sed! Officia quam omnis architecto maiores aut excepturi recusandae ullam necessitatibus commodi, eveniet dolore aliquam quod enim beatae error veritatis iste nostrum accusantium quasi ipsam? Et. </p>
    

    </>
  )
}

export default About
