import React from 'react'

const Lazy =  () => {
  return (
  <>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.</p>
  
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.</p>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariat
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur.
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores aliquid saepe, quidem perspiciatis adipisci dicta doloribus possimus, provident aut vitae error amet voluptatum ipsam nostrum officiis distinctio consequuntur reiciendis, tempora sint. Labore eveniet consectetur omnis, ipsa veritatis asperiores laudantium veniam nisi, in earum praesentium totam quisquam quo quas minima non! Illum, laboriosam obcaecati! Aspernatur, non? Esse laborum alias aliquam saepe
     consequatur, nisi maiores mollitia accusamus dolor natus quibusdam unde ab molestias ullam velit quo? Nobis aut odit quos cum, nemo cumque illo impedit iusto labore! Dolorum saepe illum iure, quaerat ipsam eligendi asperiores, aliquid in ullam, culpa ducimus? Dolorum, pariatur</p>
  

  </>
  )
}

export default Lazy
